spring:
  profiles:
    active: dev
    
---
spring:
  profiles: dev
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: false #表示是否想eureka注册中心注册自己
    fetch-registry: false
    service-url:
      #重写springcloud默认的eureka服务路径http://localhost:8761/eureka/
      defaultZone: http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/ #将其他集群的连接添加进来，多个之间用逗号隔开



---

spring:
  profiles: dev
server:
  port: 7001
eureka:
  instance:
    hostname: eureka7001
  client:
    register-with-eureka: false #表示是否想eureka注册中心注册自己
    fetch-registry: false
    service-url:
      #重写springcloud默认的eureka服务路径http://localhost:8761/eureka/
      defaultZone: http://eureka7002:7002/eureka/,http://eureka7003:7003/eureka/ #将其他集群的连接添加进来，多个之间用逗号隔开
