spring:
  profiles:
    active: dev
    
---
server:
  port: 8001
spring:
  profiles: dev
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: thinker

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.bai.pojo
#eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka,http://eureka7003:7003/eureka  #此处对应eureka服务端设置的eureka:instance:hostname
  instance:
    prefer-ip-address: true #向eureka服务端注册自己
    instance-id: springcloud-provider8001 #eureka页面上服务的状态实例名称

---
server:
  port: 8001
spring:
  profiles: test
  application:
    name: springcloud-provider-dept
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/db01?useUnicode=true&characterEncoding=utf-8
    username: root
    password: thinker

mybatis:
  mapper-locations: classpath:mybatis/*.xml
  type-aliases-package: com.bai.pojo
#eureka的配置，服务注册到哪里
eureka:
  client:
    service-url:
      defaultZone: http://eureka7001:7001/eureka/,http://eureka7002:7002/eureka,http://eureka7003:7003/eureka  #此处对应eureka服务端设置的eureka:instance:hostname
  instance:
    prefer-ip-address: true #向eureka服务端注册自己
    instance-id: springcloud-provider8001 #eureka页面上服务的状态实例名称